<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecture" nsURI="http://architecture/1.0" nsPrefix="architecture">
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cliente" lowerBound="1"
        eType="#//Cliente"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servidor" lowerBound="1"
        eType="#//Servidor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cliente">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rutas" lowerBound="2" upperBound="2"
        eType="#//Ruta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ruta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vistas" lowerBound="1"
        upperBound="-1" eType="#//Vista"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vista">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelo" lowerBound="1"
        eType="#//Modelo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modelo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" lowerBound="1"
        eType="#//Template"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Servidor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlador" lowerBound="1"
        eType="#//Controlador"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controlador">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logica" lowerBound="1"
        eType="#//Logica"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Logica">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" lowerBound="1"
        upperBound="-1" eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operaciones" lowerBound="1"
        upperBound="-1" eType="#//Operaciones"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metodos" upperBound="-1"
        eType="#//Metodo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metodo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributosEntrada" upperBound="-1"
        eType="#//Atributo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributosSalida" eType="#//Atributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operaciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subOperaciones" upperBound="-1"
        eType="#//Operaciones"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoOperacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidad" lowerBound="1"
        eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precedencia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
