<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="problemdomain" nsURI="http://problemdomain/1.0" nsPrefix="problemdomain">
  <eClassifiers xsi:type="ecore:EClass" name="Sistema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Contactos" lowerBound="1"
        eType="#//Contacto" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Pagos" lowerBound="1" eType="#//RegistroPago"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InfoSistema" upperBound="-1"
        eType="#//Caracteristica"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SistemaArticulos" lowerBound="1"
        eType="#//Articulo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Articulo" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Caracteristicas" upperBound="-1"
        eType="#//Caracteristica"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ArticuloOperaciones" upperBound="-1"
        eType="#//Operacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contacto" eSuperTypes="#//TipoDato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Articulos" upperBound="-1"
        eType="#//Articulo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InfoContacto" upperBound="-1"
        eType="#//Caracteristica"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ContactoOperaciones" upperBound="-1"
        eType="#//Operacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operando" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehiculo"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegistroPago">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Articulo" lowerBound="1"
        eType="#//Articulo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Pagador" lowerBound="1"
        eType="#//Contacto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Datos" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InfoDePago" eType="#//Caracteristica"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RegistroPagoOperaciones"
        upperBound="-1" eType="#//Operacion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//Expresion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Caracteristica">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoDato" lowerBound="1"
        eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esOperando" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoDato" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//TipoDato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//TipoDato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//TipoDato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//TipoDato"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTime" eSuperTypes="#//TipoDato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoEntrada" upperBound="-1"
        eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoDatoRetorno" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OperacionParametros" upperBound="-1"
        eType="#//Parametro"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//TipoDato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parametro">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoDatoParametro" lowerBound="1"
        eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expresion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="izq" lowerBound="1" eType="#//Expresion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="der" lowerBound="1" eType="#//Expresion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipo" lowerBound="1" eType="#//Operando.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operando" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valor" eSuperTypes="#//Operando.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signo" eSuperTypes="#//Operando.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Suma" eSuperTypes="#//Expresion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resta" eSuperTypes="#//Expresion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicacion" eSuperTypes="#//Expresion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//Expresion"/>
</ecore:EPackage>
